name: Release and Publish
on:
  push:
    # 监听 dev 分支的 push 事件
    branches:
      - dev
# 赋予 release-please-action 权限
permissions:
  contents: write
  pull-requests: write
jobs:
  # 设置 release-please 任务
  release-please:
    # 设置任务运行环境为 ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      # 使用 release-please-action 动作来自动创建发布 PR
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          # 设置发布类型为 node
          release-type: node
          # 设置包名
          package-name: karin-plugin-Group
          # 设置发布PR分支
          default-branch: dev
      # 检出代码
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}